### ISSUE TITLE
Fails at the restore to HD-USB

### ISSUE THREAD

**Issue by Rippli** [chris1111/macOS-Catalina-HD#1]
![Screenshot 2020-03-05 at 15 59 07](https://user-images.githubusercontent.com/5859772/76000544-c568bf80-5efb-11ea-8c5e-38e692642071.png)

Issue [fix here](https://github.com/chris1111/macOS-Catalina-HD/issues/1#issuecomment-597088680)

**Comment by Rippli** [comment]
Volume was renamed, but nothing copied across. Log attached.
[AutoDMG 2020-03-05 15.56.log](https://github.com/chris1111/macOS-Catalina-HD/files/4293933/AutoDMG.2020-03-05.15.56.log)

**Comment by chris1111** [comment]
> Volume was renamed, but nothing copied across. Log attached.
> [AutoDMG 2020-03-05 15.56.log](https://github.com/chris1111/macOS-Catalina-HD/files/4293933/AutoDMG.2020-03-05.15.56.log)

This log is OK

**Comment by Rippli** [comment]
Hi Chris, sorry I was not clear, I think the log is OK. The program fails at the very end (see screen shot) It renames the USB-HD to "Catalina_HD" then has an execution error and ends.
Nothing is copied to the new volume. Any idea why it fails?
Thank you!
![76000544-c568bf80-5efb-11ea-8c5e-38e692642071](https://user-images.githubusercontent.com/5859772/76034313-7c822c80-5f36-11ea-9182-7ddccc8774e9.png)

**Comment by chris1111** [comment]
why you rename
See video correctly

**Comment by Rippli** [comment]
Hi Chris,
No - I did not rename.
Your script renamed volume from HD-USB >to > Catalina_HD as on video.
Then 0:188 execution error. Does not validate or replicate. No files are copied to Cataline_HD
-----
You will have to exit AutoDMG at the end
of the process to restore your disk image.
Be patient . . . 
**********************************************  
Volume on disk3s1 renamed to Catalina_HD
0:188: execution error: Usage: asr <verb> <options>
  <verb> is one of the following:
    asr help | version
    asr restore --source <source> --target <target> [<options>]
    asr restore --source asr://<host>/ --file <file> [<options>]
    asr server  --source <source> --config <plist> [<options>]
    asr imagescan --source <source> [--filechecksum] [--nostream]
    asr info --source <source> [--plist] (64)
"disk4" ejected.
  
2020-03-06 10:38:24
********************************************** 
Restore Complete! 
**********************************************

**Comment by chris1111** [comment]
Are you on Mojave or Catalina ?
If you are on Mojave I don't think its work
If you are on VM, this is not working on Virtual machine

**Comment by Rippli** [comment]
I am on Catalina (10.15.2)
No, not VM. I am using an imac

**Comment by chris1111** [comment]
the test is running on 10.15.3 10.15.2 is full of bug!

**Comment by Rippli** [comment]
Hi Chris, I have updated the iMac to 10.15.3 and ran your script again.

Same error:


You will have to exit the Disk utility at the end of the process. 
**********************************************  
AutoDMG startup, creation process and Install image!
  
You will have to exit AutoDMG at the end
of the process to restore your disk image.
Be patient . . . 
**********************************************  
Volume on disk3s1 renamed to Catalina_HD
0:188: execution error: Usage: asr <verb> <options>
  <verb> is one of the following:
    asr help | version
    asr restore --source <source> --target <target> [<options>]
    asr restore --source asr://<host>/ --file <file> [<options>]
    asr server  --source <source> --config <plist> [<options>]
    asr imagescan --source <source> [--filechecksum] [--nostream]
    asr info --source <source> [--plist] (64)
28:312: execution error: System Events got an error: AppleEvent timed out. (-1712)
"disk4" ejected.
  
2020-03-09 10:01:47
********************************************** 
Restore Complete! 
********************************************** 



An OSX dialogue box says:
0: APFS Restore of Drive Restore Complete
File osx-10.15.3-19D76.apfs.dmg
Size 10.67 GB 
COMPLETE

But nothing has been copied to HD (USB)

Any more ideas?

**Comment by chris1111** [comment]
no idea sorry ?
Maybe a materiel issue ?

**Comment by Rippli** [comment]
materiel issue ?? 
- do you mean the SSD?
It is a new Samsung 860EVO 500gb.
I will try a different HD.
Thank you

**Comment by chris1111** [comment]
Maybe the external  enclosure case ?

**Comment by Rippli** [comment]
Not using an enclosure.
I am using a USB to SATA cable. I will try using a HD in an enclosure.

**Comment by Rippli** [comment]
Hi Chris,
I tried again with a La Cie external HD, using an iMac with Catalina 10.15.3

There was an extra dialog box this time asking for password to run a script...
Reports success, but HD is empty - nothing is restored.

​"disk3" ejected.
2020-03-10 09:40:38
Starting macOS Catalina HD
button returned:Creation
created: /tmp/Install-macOS.sparseimage
/dev/disk3          	GUID_partition_scheme          	
/dev/disk3s1        	EFI                            	
/dev/disk3s2        	Apple_HFS                      	/Volumes/Install-macOS
**********************************************  
 
You can continue with the program. 
**********************************************  
 
You will have to exit the Disk utility at the end of the process. 
**********************************************  
AutoDMG startup, creation process and Install image!
  
You will have to exit AutoDMG at the end
of the process to restore your disk image.
Be patient . . . 
**********************************************  
Volume on disk4s1 renamed to Catalina_HD
0:188: execution error: Usage: asr <verb> <options>
  <verb> is one of the following:
    asr help | version
    asr restore --source <source> --target <target> [<options>]
    asr restore --source asr://<host>/ --file <file> [<options>]
    asr server  --source <source> --config <plist> [<options>]
    asr imagescan --source <source> [--filechecksum] [--nostream]
    asr info --source <source> [--plist] (64)
"disk3" ejected.
  
2020-03-10 10:16:58
********************************************** 
Restore Complete! 
********************************************** 


Any more ideas?

**Comment by chris1111** [comment]
Strange because Its work using my [MacBook Pro](https://support.apple.com/kb/SP691?viewlocale=en_US&locale=fr_CA) also works using all of my other Mac and Hackintosh

**Comment by Rippli** [comment]
Hi Chris,
Good news! I tried again, using a different iMac and the Samsung SSD connected with USB/SATA cable.
Seems to have been successful.
If it helps you:
SUCCESSFUL iMac = late 2012 - 21", 2.5GHz i5,  OSX 10.15.3, 1TB HD, 8GB Ram
FAIL iMac = late 2012 - 27" 2.9Ghz i5, OSX 10.15.3, 500GB SSD, 24GB Ram

Thank you for all your responses. I will donate to your Forum.
Paul

**Comment by chris1111** [comment]
thanks i'm glad to see that it worked for you
